# Generated by Django 2.2.19 on 2021-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id主键')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户数据',
                'verbose_name_plural': '用户数据',
                'db_table': 'users',
            },
        ),
    ]
